services:
  database:
    container_name: ${DOCKER_DATABASE_CONTAINER_NAME}
    image: postgres:15
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    container_name: ${DOCKER_PGADMIN_CONTAINER_NAME}
    image: dpage/pgadmin4
    restart: always
    ports:
      - "${PGADMIN_PORT}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - database

  backend:
    container_name: ${DOCKER_BACKEND_CONTAINER_NAME}
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "${PORT}:3000"
    depends_on:
      - database
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  pgdata:
